name: Publish Docker image

on:
  push:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up environment variables
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_AUTH_SERVICE_BASEURL=${{ secrets.VITE_AUTH_SERVICE_BASEURL }}" >> .env
          echo "VITE_AUTH_SERVICE_ADMIN_BASEURL=${{ secrets.VITE_AUTH_SERVICE_ADMIN_BASEURL }}" >> .env
          echo "VITE_AUTH_SERVICE_ADMIN_BASEURL=${{ secrets.VITE_AUTH_SERVICE_ADMIN_BASEURL }}" >> .env
          echo "VITE_AUTH_SERVICE_ADMIN_BASEURL=${{ secrets.VITE_AUTH_SERVICE_ADMIN_BASEURL }}" >> .env
          echo "VITE_GROUP_SERVICE_BASEURL=${{ secrets.VITE_GROUP_SERVICE_BASEURL }}" >> .env
          echo "VITE_CHAT_SERVICE_BASEURL=${{ secrets.VITE_CHAT_SERVICE_BASEURL }}" >> .env
          echo "VITE_ZEGO_CLOUD_SERVER_SECRET=${{ secrets.VITE_ZEGO_CLOUD_SERVER_SECRET }}" >> .env
          echo "VITE_ZEGO_CLOUD_APP_ID=${{ secrets.VITE_ZEGO_CLOUD_APP_ID }}" >> .env
         
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: adarshbinomon/echoblog-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: adarshbinomon/echoblog-frontend:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Fetch Kubernetes credentials
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}

      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment/client-deployment
